-- AlterTable
ALTER TABLE "ClockAmendment" ADD COLUMN     "approvalNote" TEXT,
ADD COLUMN     "chaseCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "chasedAt" TIMESTAMP(3),
ADD COLUMN     "clientSignatureUrl" TEXT,
ADD COLUMN     "clockName" TEXT,
ADD COLUMN     "clockRow" JSONB,
ADD COLUMN     "dsnPdfUrl" TEXT,
ADD COLUMN     "intakeActualIn" TEXT,
ADD COLUMN     "intakeActualOut" TEXT,
ADD COLUMN     "intakeReasonCode" TEXT,
ADD COLUMN     "intakeReasonText" TEXT,
ADD COLUMN     "note" JSONB,
ADD COLUMN     "notesName" TEXT,
ADD COLUMN     "pdfHash" TEXT,
ADD COLUMN     "pdfUrl" TEXT,
ADD COLUMN     "qspFixedAt" TIMESTAMP(3),
ADD COLUMN     "qspFixedBy" TEXT,
ADD COLUMN     "qspFixedTo" TEXT,
ADD COLUMN     "staffSignatureUrl" TEXT,
ADD COLUMN     "testOnly" BOOLEAN NOT NULL DEFAULT false;
